# Generated by Django 6.0.7 on 2026-07-30 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='created',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='minimum_age',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='created',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='name',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='updated',
        ),
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.categories'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('postventa', 'Ejecutivo Postventa'), ('ejecutivo_logistica', 'Ejecutivo de Logística'), ('operador_logistica', 'Operador de Logística'), ('administrador', 'Administrador')], default='postventa', max_length=30, verbose_name='Rol en la Plataforma'),
        ),
    ]
