# Generated by Django 6.0.7 on 2026-08-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_solicituddevolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddevolucion',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='solicituddevolucion',
            name='producto',
            field=models.CharField(default='Sin producto', max_length=200, verbose_name='Nombre o Código del Producto'),
            preserve_default=False,
        ),
    ]
