# Generated by Django 6.1 on 2026-08-23 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_categories_id_alter_movies_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='solicituddevolucion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa / Proveedor de Excedentes'), ('cliente', 'Cliente / Comprador B2B')], default='cliente', max_length=20)),
                ('empresa_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoInverso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('codigo_ean', models.CharField(help_text='Código EAN-13 real del producto', max_length=13, unique=True)),
                ('volumen_lote', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades en el lote')),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_rescate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_fisico', models.CharField(help_text='Ej: Caja dañada, Próximo a caducar, Retorno', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgendamientoLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repartidor_asignado', models.CharField(max_length=100)),
                ('cliente_empresa', models.CharField(max_length=150)),
                ('fecha_recogida', models.DateField()),
                ('franja_horaria', models.CharField(help_text='Ej: 09:00 - 12:00', max_length=50)),
                ('estado_envio', models.CharField(default='Pendiente de retiro', max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.productoinverso')),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.DeleteModel(
            name='SolicitudDevolucion',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
