# Generated by Django 6.1 on 2026-08-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movies_category_remove_movies_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinverso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productoinverso',
            name='marca',
            field=models.CharField(blank=True, help_text='Ej: Levis, Opposite', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productoinverso',
            name='tienda_origen',
            field=models.CharField(blank=True, help_text='Ej: Falabella, Hites', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productoinverso',
            name='ubicacion',
            field=models.CharField(blank=True, default='Santiago, Chile', max_length=150, null=True),
        ),
    ]
