# Generated by Django 6.1 on 2026-08-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_productoinverso_created_at_productoinverso_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinverso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_inversos/'),
        ),
        migrations.AlterField(
            model_name='productoinverso',
            name='marca',
            field=models.CharField(blank=True, help_text="Ej: Levi's, Opposite", max_length=100, null=True),
        ),
    ]
