# Generated by Django 6.1 on 2026-08-24 00:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_productoinverso_imagen_alter_productoinverso_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='empresa_nombre',
        ),
        migrations.RemoveField(
            model_name='productoinverso',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productoinverso',
            name='imagen',
        ),
        migrations.AddField(
            model_name='agendamientologistica',
            name='fecha_agendamiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productoinverso',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendamientologistica',
            name='estado_envio',
            field=models.CharField(default='Agendado / Pendiente de retiro', max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamientologistica',
            name='franja_horaria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamientologistica',
            name='repartidor_asignado',
            field=models.CharField(default='Flota B2B Express', max_length=150),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente / Comprador B2B'), ('empresa', 'Empresa / Proveedor')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='productoinverso',
            name='codigo_ean',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='productoinverso',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos_inversos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoinverso',
            name='estado_fisico',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productoinverso',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productoinverso',
            name='tienda_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productoinverso',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productoinverso',
            name='volumen_lote',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos_inversos/')),
                ('es_principal', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='movies.productoinverso')),
            ],
        ),
    ]
