# Generated by Django 6.1 on 2026-08-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_perfilusuario_empresa_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamientologistica',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agendamientologistica',
            name='direccion_receptor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agendamientologistica',
            name='nombre_receptor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='agendamientologistica',
            name='telefono_receptor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agendamientologistica',
            name='tipo_entrega',
            field=models.CharField(default='retiro', max_length=50),
        ),
        migrations.AddField(
            model_name='agendamientologistica',
            name='tipo_pago',
            field=models.CharField(default='debito', max_length=50),
        ),
        migrations.AddField(
            model_name='agendamientologistica',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
