# Generated by Django 6.1 on 2026-08-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_agendamientologistica_costo_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamientologistica',
            name='fecha_recogida',
            field=models.DateTimeField(),
        ),
    ]
