# Generated by Django 6.1 on 2026-08-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_agendamientologistica_fecha_recogida'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinverso',
            name='categoria',
            field=models.CharField(choices=[('ropa', 'Ropa'), ('electrodomesticos', 'Electrodomésticos'), ('tecnologia', 'Tecnología')], default='tecnologia', max_length=50),
        ),
    ]
