# Generated by Django 6.1 on 2026-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_productoinverso_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoinverso',
            name='categoria',
            field=models.CharField(choices=[('ropa', 'Ropa'), ('electrodomesticos', 'Electrodomésticos'), ('tecnologia', 'Tecnología')], max_length=50),
        ),
    ]
