# Generated by Django 6.1 on 2026-08-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_productoinverso_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamientologistica',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='agendamientologistica',
            name='franja_horaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
